version = 1

exclude_patterns = [
    "setup/**",
    "comp/**",
    "app_res/**",
    "app/data/**",
    "app/cudatext.app/Contents/Resources/data/**"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"